name: example
description: An example of using vsc_quill_delta_to_html in Flutter and on server-side (or CLI) Dart.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  vsc_quill_delta_to_html:
    path: ../
  flutter_quill: ^8.6.4
  url_launcher: ^6.1.2
  webviewx_plus: ^0.4.1
  flex_color_picker: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
