name: vsc_quill_delta_to_html
description: A quill Delta to HTML converter. Ported from the JS library https://www.npmjs.com/package/quill-delta-to-html.
version: 1.0.0
homepage: https://vscorp.com

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  html_unescape: ^2.0.0
  collection: ^1.16.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
